# Changes here will be overwritten by Copier
_commit: 7cb1c26
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Alias for spaday-webawesome
project_name: spaday-shoelace
python_version_primary: '3.11'
team: 1kbgz
